spring.application.name=clinica
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/clinica_bd
spring.datasource.username=postgres
spring.datasource.password=021316
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true